AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  PublicSubnetId: { Type: String }
  PrivateSubnetId: { Type: String }
  PublicSGId: { Type: String }
  PrivateSGId: { Type: String }
  KeyName: { Type: String }

Resources:
  PublicEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-07ff62358b87c7116
      InstanceType: t3.small
      SubnetId: !Ref PublicSubnetId
      SecurityGroupIds: [!Ref PublicSGId]
      KeyName: !Ref KeyName
      Tags: [{ Key: Name, Value: Public-EC2 }]

  PrivateEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-07ff62358b87c7116
      InstanceType: t3.small
      SubnetId: !Ref PrivateSubnetId
      SecurityGroupIds: [!Ref PrivateSGId]
      KeyName: !Ref KeyName
      Tags: [{ Key: Name, Value: Private-EC2 }]

Outputs:
  PublicInstanceIP: { Value: !GetAtt PublicEC2.PublicIp }
  PrivateInstanceIP: { Value: !GetAtt PrivateEC2.PrivateIp }